// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kewypxmulhhxwxhxehhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtld3lweG11bGhoeHd4aHhlaGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzQ5MzAsImV4cCI6MjA2MjY1MDkzMH0.FjVsEceJEd6RjfsA1gsZMYs09RPzFI34gkJolQe43Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);